# Generated by Django 3.1.7 on 2021-12-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211212_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discount_price',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
