# Generated by Django 3.1.7 on 2021-12-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211212_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
